# Generated by Django 4.2 on 2023-11-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employes_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employes',
            old_name='images',
            new_name='profile_pic',
        ),
    ]
